"version": "3.7"

services:

  flask:
    image: eduardgrinberg/firewave-poc-be_flask
    build: ./flaskApp
    container_name: flask
    restart: always
    environment:
      - APP_NAME=FlaskApp
    expose:
      - 8080

  nginx:
    image: eduardgrinberg/firewave-poc-be_nginx
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"