#!/bin/bash

echo 'Running move-files'

while true
do
    dirlist=$(ls /home/ec2-user/data/archive/)
    for file in $dirlist
    do
        aws s3 cp /home/ec2-user/data/archive/$file s3://firewave-recordings
        rm /home/ec2-user/data/archive/$file
    done
    sleep 10
done