#!/bin/bash

echo 'remove containers'

docker stop flask
docker stop nginx
docker system prune -af

echo 'clone code, build images and run containers'

cd /home/ec2-user/
rm -rf source
git clone https://github.com/eduardgrinberg/firewave-poc-be.git source
docker image build -t nginx:latest source/nginx
docker image build -t flask:latest source/flaskApp
docker network create -d bridge firewave-poc-be-nt
docker run -d --net firewave-poc-be-nt --restart always -v /home/ec2-user/data:/app/data --name flask flask:latest
docker run -d --net firewave-poc-be-nt --restart always --name nginx -p 5000:80 nginx:latest

echo 're-install and run move-files.service'

cd /home/ec2-user/source/bash/
sudo chmod +x re-install-move-files
sudo chmod +x move-files

sudo ./re-install-move-files